const BASE = 'https://api.themoviedb.org/3';
const KEY = process.env.TMDB_API_KEY;
const IMG = 'https://image.tmdb.org/t/p';

// Nosso addon usa 'series', TMDB usa 'tv'
const tmdbType = (type) => type === 'series' ? 'tv' : 'movie';

function normalizeTitle(s) {
  return (s || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

const GENERIC_KEYWORDS = new Set([
  'based on novel', 'based on novel or book', 'sequel', 'prequel', 'remake',
  'based on comic', 'based on comic book', 'based on true story', 'biography',
  'duringcreditsstinger', 'aftercreditsstinger', 'post-credits scene',
  'female protagonist', 'male protagonist', 'woman director',
  'death', 'murder', 'friendship', 'betrayal', 'violence', 'drug', 'alcohol',
  'war', 'soldier', 'police', 'detective', 'love', 'revenge',
  'coming of age', 'teenage', 'high school', 'flashback', 'voice over',
  'independent film', 'ensemble cast', 'cameo', 'satire', 'based on manga',
  'crime', 'action hero', 'spy', 'heist', 'prison', 'father son relationship',
  'alien', 'monster', 'zombie', 'vampire', 'ghost', 'superhero',
]);

const TMDB_MAX_429_RETRIES = 2;   // teto de re-tentativas em 429 (evita loop infinito)
const TMDB_MAX_WAIT_S = 10;       // teto do Retry-After honrado (evita worker preso)
const tmdbSleep = (ms) => new Promise(r => setTimeout(r, ms));

// opts.{ fetchImpl, sleep, attempt } são injetáveis para teste (sem rede/espera).
async function tmdbFetch(path, params = {}, opts = {}) {
  const fetchImpl = opts.fetchImpl || fetch;
  const sleep = opts.sleep || tmdbSleep;
  const attempt = opts.attempt || 0;

  const url = new URL(`${BASE}${path}`);
  url.searchParams.set('api_key', KEY);
  url.searchParams.set('language', process.env.TMDB_LANGUAGE || 'en-US');
  for (const [k, v] of Object.entries(params)) {
    if (v !== undefined && v !== null) url.searchParams.set(k, String(v));
  }
  let res;
  try {
    res = await fetchImpl(url.toString(), { signal: AbortSignal.timeout(15000) });
  } catch (err) {
    console.warn(`[tmdb] fetch failed ${path}:`, err.message);
    return null;
  }
  if (res.status === 429) {
    if (attempt >= TMDB_MAX_429_RETRIES) {
      console.warn(`[tmdb] 429 persistente em ${path}; desistindo após ${attempt + 1} tentativas`);
      return null;
    }
    const wait = Math.min(parseInt(res.headers.get('Retry-After') || '5', 10) || 5, TMDB_MAX_WAIT_S);
    await sleep(wait * 1000);
    return tmdbFetch(path, params, { ...opts, attempt: attempt + 1 });
  }
  if (!res.ok) return null;
  return res.json();
}

// Candidates via co-viewing: recommendations generated by TMDB itself
async function getRecommendations(tmdbId, type, pages = 2) {
  const t = tmdbType(type);
  const results = [];
  for (let page = 1; page <= pages; page++) {
    const data = await tmdbFetch(`/${t}/${tmdbId}/recommendations`, { page });
    if (!data?.results?.length) break;
    results.push(...data.results);
    if (page >= (data.total_pages || 1)) break;
  }
  return results;
}

// Candidates by metadata similarity
async function getSimilar(tmdbId, type) {
  const t = tmdbType(type);
  const data = await tmdbFetch(`/${t}/${tmdbId}/similar`);
  return data?.results || [];
}

function pickBestMatch(results, { title, year }) {
  if (!Array.isArray(results) || results.length === 0) return null;
  const wanted = normalizeTitle(title);
  let best = null;
  let bestScore = -Infinity;

  const titleMatchScore = (cand) => {
    if (!cand) return 0;
    if (cand === wanted) return 5;
    if (cand.includes(wanted) || wanted.includes(cand)) return 2;
    return 0;
  };

  for (const result of results) {
    // Compara tanto o título localizado (name/title, em pt-BR pela language do fetch)
    // quanto o ORIGINAL (original_name/original_title, geralmente em inglês). Sem o
    // original, um título inglês ("The Handmaid's Tale") não casa com o nome pt-BR
    // ("O Conto da Aia") e a busca falha — derrubava seeds e candidatos da IA.
    const localized = normalizeTitle(result.title || result.name);
    const original = normalizeTitle(result.original_title || result.original_name);
    const resultYear = parseInt((result.release_date || result.first_air_date || '').slice(0, 4), 10);

    const titleScore = Math.max(titleMatchScore(localized), titleMatchScore(original));
    if (titleScore === 0) continue;
    let score = titleScore;

    if (year && resultYear) score += Math.max(0, 3 - Math.abs(resultYear - Number(year)));
    score += Math.min(2, (result.vote_count || 0) / 1000);
    score += Math.min(1, (result.popularity || 0) / 50);

    if (score > bestScore) {
      best = result;
      bestScore = score;
    }
  }

  return bestScore >= 4 ? best : null;
}

async function searchTitle(title, year, type) {
  const t = tmdbType(type);
  const params = { query: title, include_adult: 'false' };
  if (year) params[t === 'movie' ? 'year' : 'first_air_date_year'] = year;
  const data = await tmdbFetch(`/search/${t}`, params);
  return data?.results || [];
}

async function discover(type, opts = {}) {
  const t = tmdbType(type);
  const dateField = t === 'movie' ? 'primary_release_date' : 'first_air_date';
  const params = {
    sort_by: opts.sortBy || 'popularity.desc',
    'vote_count.gte': opts.voteCountGte ?? 50,
    page: opts.page || 1,
  };
  if (opts.genres?.length) params.with_genres = opts.genres.join(',');
  if (opts.keywords?.length) params.with_keywords = opts.keywords.join('|');
  if (opts.language) params.with_original_language = opts.language;
  if (opts.dateGte) params[`${dateField}.gte`] = opts.dateGte;
  if (opts.dateLte) params[`${dateField}.lte`] = opts.dateLte;
  if (opts.withoutGenres?.length) params.without_genres = opts.withoutGenres.join('|');
  const data = await tmdbFetch(`/discover/${t}`, params);
  return data?.results || [];
}

// imdb_id a partir de tmdb_id — sem busca textual, determinístico
async function getExternalIds(tmdbId, type) {
  const t = tmdbType(type);
  const data = await tmdbFetch(`/${t}/${tmdbId}/external_ids`);
  return data || {};
}

// Detalhes + external_ids em uma única chamada para enriquecer os 10 picks finais
// PURA: extrai os campos de detalhe de um payload de /{t}/{id} (com external_ids).
function parseDetails(data, tmdbId, type) {
  if (!data) return null;
  const title = data.title || data.name || '';
  const year = (data.release_date || data.first_air_date || '').slice(0, 4);
  const imdb_id = data.external_ids?.imdb_id || null;
  const poster = data.poster_path ? `${IMG}/w500${data.poster_path}` : null;
  const backdrop = data.backdrop_path ? `${IMG}/w1280${data.backdrop_path}` : null;
  const vote_average = Math.round((data.vote_average || 0) * 10) / 10;
  const genres = (data.genres || []).map(g => g.name);
  const overview = data.overview || '';
  const original_language = data.original_language || '';
  const origin_country = data.origin_country || (data.production_countries || []).map(c => c.iso_3166_1).filter(Boolean);
  const runtime = type === 'movie'
    ? (data.runtime ? `${data.runtime} min` : null)
    : (data.episode_run_time?.[0] ? `${data.episode_run_time[0]} min/ep` : null);

  const vote_count = data.vote_count || 0;
  const popularity = data.popularity || 0;

  return { tmdb_id: tmdbId, imdb_id, title, year, poster, backdrop, vote_average, vote_count, popularity, genres, runtime, overview, original_language, origin_country };
}

// PURA: extrai diretores/elenco de um payload combinado (movie: credits / tv: aggregate_credits).
function parseCredits(data, type) {
  if (type === 'movie') {
    return {
      directors: (data.credits?.crew || []).filter(c => c.job === 'Director').map(c => ({ id: c.id, name: c.name })),
      cast: (data.credits?.cast || []).slice(0, 5).map(c => ({ id: c.id, name: c.name })),
    };
  }
  return {
    directors: (data.created_by || []).map(c => ({ id: c.id, name: c.name })),
    cast: (data.aggregate_credits?.cast || []).slice(0, 5).map(c => ({ id: c.id, name: c.name })),
  };
}

// PURA: keywords filtradas pela denylist (movie usa .keywords, tv usa .results).
function parseKeywords(data) {
  const raw = data.keywords?.keywords || data.keywords?.results || [];
  return raw.filter(k => k.name && !GENERIC_KEYWORDS.has(k.name.toLowerCase()));
}

async function getDetails(tmdbId, type) {
  const t = tmdbType(type);
  const data = await tmdbFetch(`/${t}/${tmdbId}`, { append_to_response: 'external_ids' });
  return parseDetails(data, tmdbId, type);
}

// Detalhes + créditos + keywords numa ÚNICA chamada (append_to_response) — 3×
// menos round-trips que getDetails+getCredits+getKeywords. Usado no enriquecimento
// (o caminho quente: ~50 candidatos × 6 prateleiras). Retorna o mesmo shape que
// normalizeMediaPayload consome: { details, credits, keywords }.
async function getFullMedia(tmdbId, type) {
  const t = tmdbType(type);
  const append = t === 'movie'
    ? 'external_ids,credits,keywords'
    : 'external_ids,aggregate_credits,keywords';
  const data = await tmdbFetch(`/${t}/${tmdbId}`, { append_to_response: append });
  if (!data) return { details: null, credits: {}, keywords: [] };
  return {
    details: parseDetails(data, tmdbId, type),
    credits: parseCredits(data, type),
    keywords: parseKeywords(data),
  };
}

async function getCredits(tmdbId, type) {
  const t = tmdbType(type);
  if (t === 'movie') {
    const data = await tmdbFetch(`/movie/${tmdbId}/credits`);
    return {
      directors: (data?.crew || []).filter(c => c.job === 'Director').map(c => ({ id: c.id, name: c.name })),
      cast: (data?.cast || []).slice(0, 5).map(c => ({ id: c.id, name: c.name })),
    };
  }

  const data = await tmdbFetch(`/tv/${tmdbId}`, { append_to_response: 'aggregate_credits' });
  return {
    directors: (data?.created_by || []).map(c => ({ id: c.id, name: c.name })),
    cast: (data?.aggregate_credits?.cast || []).slice(0, 5).map(c => ({ id: c.id, name: c.name })),
  };
}

// Keywords for a title for new releases, already filtered by denylist
async function getKeywords(tmdbId, type) {
  const t = tmdbType(type);
  const path = t === 'movie' ? `/movie/${tmdbId}/keywords` : `/tv/${tmdbId}/keywords`;
  const data = await tmdbFetch(path);
  const raw = data?.keywords || data?.results || [];
  return raw.filter(k => !GENERIC_KEYWORDS.has(k.name.toLowerCase()));
}

// /discover for new releases: recent data + top keywords in OR
async function discoverByDateAndKeywords(type, keywordIds) {
  const t = tmdbType(type);
  const since = new Date();
  since.setMonth(since.getMonth() - 18);
  const dateStr = since.toISOString().slice(0, 10);
  const dateParam = t === 'movie' ? 'primary_release_date.gte' : 'first_air_date.gte';

  const params = {
    sort_by: 'vote_average.desc',
    'vote_count.gte': 20,
    [dateParam]: dateStr,
  };
  if (keywordIds.length > 0) {
    params.with_keywords = keywordIds.join('|'); // OR — mais abrangente que AND
  }

  const results = [];
  for (let page = 1; page <= 3; page++) {
    const data = await tmdbFetch(`/discover/${t}`, { ...params, page });
    if (!data?.results?.length) break;
    results.push(...data.results);
    if (page >= (data.total_pages || 1)) break;
  }
  return results;
}

// Trending semanal por tipo (movie ou series/tv)
async function getTrending(type) {
  const t = tmdbType(type);
  const data = await tmdbFetch(`/trending/${t}/week`);
  return data?.results || [];
}

// Busca tmdb_id + tipo a partir de um imdb_id via /find
async function getByImdb(imdbId) {
  if (!imdbId) return null;
  const data = await tmdbFetch(`/find/${imdbId}`, { external_source: 'imdb_id' });
  if (!data) return null;
  const movie = (data.movie_results || [])[0];
  if (movie) return { tmdb_id: movie.id, type: 'movie' };
  const tv = (data.tv_results || [])[0];
  if (tv) return { tmdb_id: tv.id, type: 'series' };
  return null;
}

module.exports = {
  getRecommendations,
  getSimilar,
  searchTitle,
  discover,
  getExternalIds,
  getDetails,
  getCredits,
  getKeywords,
  getFullMedia,
  parseDetails,
  parseCredits,
  parseKeywords,
  tmdbFetch,
  discoverByDateAndKeywords,
  getTrending,
  getByImdb,
  tmdbType,
  pickBestMatch,
  normalizeTitle,
};
